# Generated by Django 5.0.4 on 2024-04-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0003_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
