# Generated by Django 5.0.4 on 2024-04-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0005_rename_code_otpcode_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='otp_code',
            new_name='code',
        ),
    ]
