# Generated by Django 5.0.4 on 2024-04-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0006_rename_otp_code_otpcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_creation',
            new_name='post_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time_creation',
            new_name='post_time',
        ),
    ]
