# Generated by Django 5.0.4 on 2024-04-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0007_rename_time_creation_comment_post_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_time']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ru',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adsboard.comment'),
        ),
    ]
