# Generated by Django 5.0.4 on 2024-04-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0008_alter_comment_options_remove_post_content_en_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
