# Generated by Django 5.0.4 on 2024-04-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsboard', '0009_rename_text_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='commentpost',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
